LOCALDIR := sys-generic

OBJS	+= \
	$(LOCALDIR)/console.o \
	$(LOCALDIR)/display.o \
	$(LOCALDIR)/mainmem.o \
	$(LOCALDIR)/net.o \
	$(LOCALDIR)/pic.o \
	$(LOCALDIR)/pit.o \
	$(LOCALDIR)/debug.o \
	$(LOCALDIR)/sys.o
